@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}



### Funciona com titulos de empresas
GET http://{{host}}/geocode/location?address=Google Belo Horizonte HTTP/1.1


### Em buscas de endereços, se deve especificar o tipo como Av ou Rua
GET http://{{host}}/geocode/location?address=Av dos Andradas 3000 Belo Horizonte HTTP/1.1


### Caso contrário não funciona
GET http://{{host}}/geocode/location?address=dos Andradas, 3000 Belo Horizonte HTTP/1.1
