@hostname = localhost
@port = 8000
@api_version=v1
@host = {{hostname}}:{{port}}/api/{{api_version}}


### Empresas
GET http://{{host}}/search?term=Google Belo Horizonte HTTP/1.1

### Ponto de referência
GET http://{{host}}/search?term=Lagoa da Pampulha HTTP/1.1

### Em buscas de endereços, se deve especificar o tipo como Av ou Rua
GET http://{{host}}/search?term=Av dos Andradas 3000 Belo Horizonte HTTP/1.1
