@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}


### Empresas
GET http://{{host}}/search?term=Google Belo Horizonte HTTP/1.1

### Ponto de referência
GET http://{{host}}/search?term=Lagoa da Pampulha HTTP/1.1

### Em buscas de endereços, se deve especificar o tipo como Av ou Rua
GET http://{{host}}/search?term=Av dos Andradas 3000 Belo Horizonte HTTP/1.1

### Caso contrário não funciona
GET http://{{host}}/search?term=dos Andradas, 3000 Belo Horizonte HTTP/1.1

###
GET http://{{host}}/search?term=Rua São Sebastião do Maranhão HTTP/1.1
